import { escapeHtml } from "../format.js";
import { cardLink, breadcrumb, emptyState } from "../ui.js";

const FILES = {
  plan: { path: ".colaberry/plan.json", note: "The delivery plan: requirements, stories, releases, and derived facts (roles, systems, guardrails, measures)." },
  progress: { path: ".colaberry/progress.json", note: "Verification state: which stories are done, which acceptance criteria passed, points awarded." },
  manifest: { path: ".colaberry/manifest.json", note: "A single timestamp — when this data was last generated by the portal." },
  profile: { path: ".colaberry/profile.json", note: "Portfolio publish settings for this project." },
};

function summarizeValue(v) {
  if (Array.isArray(v)) return `array · ${v.length} item${v.length === 1 ? "" : "s"}`;
  if (v && typeof v === "object") return `object · ${Object.keys(v).length} key${Object.keys(v).length === 1 ? "" : "s"}`;
  return typeof v;
}

function renderFileList(main, ctx) {
  const cards = Object.entries(FILES)
    .map(([key, meta]) => {
      const obj = ctx.data[key];
      const keyCount = obj ? Object.keys(obj).length : 0;
      return cardLink(
        `#/data-model/file/${encodeURIComponent(key)}`,
        `
          <div class="cc-stat-label">${escapeHtml(meta.path)}</div>
          <div class="cc-stat-value" style="font-size:16px;">${obj ? `${keyCount} top-level key${keyCount === 1 ? "" : "s"}` : "not loaded"}</div>
          <div class="cc-stat-sub">${escapeHtml(meta.note)}</div>
        `
      );
    })
    .join("");

  main.innerHTML = `
    <h1 class="cc-page-title">Data Model</h1>
    <p class="cc-page-sub">The tables behind all of the above — in this app, that's the four JSON files fetched at runtime from .colaberry/. Shapes below are read live from those files, not hand-written.</p>
    <div class="cc-card-grid">${cards}</div>
  `;
}

function renderFileDetail(main, ctx, key) {
  const meta = FILES[key];
  const obj = ctx.data[key];

  if (!meta) {
    main.innerHTML = `${breadcrumb([{ label: "Data Model", href: "#/data-model" }, { label: key }])}
      ${emptyState("Unknown file", `"${escapeHtml(key)}" is not one of the files this app reads.`)}`;
    return;
  }

  if (!obj) {
    main.innerHTML = `${breadcrumb([{ label: "Data Model", href: "#/data-model" }, { label: meta.path }])}
      ${emptyState("Not loaded", `${escapeHtml(meta.path)} failed to load or is empty on this run.`)}`;
    return;
  }

  const rows = Object.entries(obj)
    .map(([k, v]) => `<tr><td>${escapeHtml(k)}</td><td>${escapeHtml(summarizeValue(v))}</td></tr>`)
    .join("");

  main.innerHTML = `
    ${breadcrumb([{ label: "Data Model", href: "#/data-model" }, { label: meta.path }])}
    <h1 class="cc-page-title">${escapeHtml(meta.path)}</h1>
    <p class="cc-page-sub">${escapeHtml(meta.note)}</p>
    <div class="cc-table-wrap">
      <table class="cc-table">
        <thead><tr><th>Top-level key</th><th>Shape</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  `;
}

export function renderDataModel(main, ctx, rest) {
  if (rest?.[0] === "file" && rest[1]) return renderFileDetail(main, ctx, rest[1]);
  renderFileList(main, ctx);
}
